/* Mirror of jumptw-weekly-report/sql/adhoc/hisoka_participation_depth_arppu.sql */
WITH event_def AS (SELECT '佩恩' period,102 gacha_id,DATE '2026-07-15' start_date,DATE '2026-07-21' end_date UNION ALL SELECT '西索',103,DATE '2026-07-29',DATE '2026-08-04'),
blacklist AS (SELECT DISTINCT "#varchar_id" account_id FROM user_result_cluster_23 WHERE cluster_name IN ('internal_users','is_water','is_water_mod','suspicious_ip')),
active AS (SELECT e.period,COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id") account_id FROM event_def e JOIN ta.v_event_23 v ON v."$part_event"='LOGIN_SUCCESS' AND v."$part_date" BETWEEN CAST(e.start_date AS VARCHAR) AND CAST(e.end_date AS VARCHAR) LEFT JOIN blacklist b ON COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=b.account_id WHERE b.account_id IS NULL GROUP BY 1,2),
wallet AS (SELECT CAST(lcxtransactionid AS VARCHAR) purchaseid,MAX(ABS(CAST(freeamount AS DOUBLE))) freeamount FROM ta.v_event_16 WHERE "$part_event"='LCX_WALLET_SPEND_TRANSACTION' AND "$part_date" BETWEEN '2026-07-15' AND '2026-08-04' GROUP BY 1),
purchases AS (SELECT e.period,COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id") account_id,regexp_replace(element_at(split(v.payload.productid,'.'),-1),'KOL$','') productid,(CAST(v.payload.curamt AS DOUBLE)-COALESCE(w.freeamount,0))/COALESCE(x.exchange,1)*(COALESCE(TRY_CAST(SPLIT(v.payload.purchaseeventpayload,'|')[3] AS INTEGER),100)/100.000) revenue_usd FROM event_def e JOIN ta.v_event_23 v ON v."$part_event"='PURCHASE' AND v."$part_date" BETWEEN CAST(e.start_date AS VARCHAR) AND CAST(e.end_date AS VARCHAR) LEFT JOIN blacklist b ON COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=b.account_id LEFT JOIN wallet w ON CAST(v.payload.purchaseid AS VARCHAR)=w.purchaseid LEFT JOIN ta_dim.ta_exchange x ON v."$part_date"=x.ex_date AND v.payload.cur=x.currency WHERE COALESCE(v.payload.validationtype,'')<>'SANDBOX_RECEIPT' AND b.account_id IS NULL),
target_draw AS (SELECT e.period,COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id") account_id,SUM(COALESCE(v.count,0)) draws FROM event_def e JOIN ta.v_event_23 v ON v."$part_event"='active_gacha' AND v."$part_date" BETWEEN CAST(e.start_date AS VARCHAR) AND CAST(e.end_date AS VARCHAR) AND CAST(v.gacha_id AS INTEGER)=e.gacha_id LEFT JOIN blacklist b ON COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=b.account_id WHERE b.account_id IS NULL GROUP BY 1,2),
user_panel AS (SELECT a.period,a.account_id,COALESCE(d.draws,0) draws,COALESCE(SUM(p.revenue_usd),0) total_revenue_usd,COALESCE(SUM(CASE WHEN p.productid='gift9' THEN p.revenue_usd ELSE 0 END),0) gift9_revenue,COALESCE(SUM(CASE WHEN p.productid='gift30' THEN p.revenue_usd ELSE 0 END),0) gift30_revenue,COALESCE(SUM(CASE WHEN p.productid='gift31' THEN p.revenue_usd ELSE 0 END),0) gift31_revenue,COALESCE(SUM(CASE WHEN p.productid='gift39' THEN p.revenue_usd ELSE 0 END),0) gift39_revenue FROM active a LEFT JOIN target_draw d ON a.period=d.period AND a.account_id=d.account_id LEFT JOIN purchases p ON a.period=p.period AND a.account_id=p.account_id GROUP BY 1,2,3),
totals AS (SELECT period,COUNT(*) active_users,COUNT_IF(total_revenue_usd>0) all_payers,SUM(total_revenue_usd) total_revenue_usd FROM user_panel GROUP BY 1),
depth AS (SELECT period,CASE WHEN draws=0 THEN '没抽' WHEN draws<40 THEN '1–39抽' WHEN draws<80 THEN '40–79抽' ELSE '80+抽' END segment,CASE WHEN draws=0 THEN 0 WHEN draws<40 THEN 1 WHEN draws<80 THEN 2 ELSE 3 END segment_order,COUNT(*) users,COUNT_IF(total_revenue_usd>0) payers,SUM(total_revenue_usd) revenue_usd,AVG(draws) avg_draws FROM user_panel GROUP BY 1,2,3),
selected_product AS (SELECT period,'gift9 限时阅览券礼包' segment,1 segment_order,COUNT_IF(gift9_revenue>0) buyers,SUM(gift9_revenue) revenue_usd FROM user_panel GROUP BY 1 UNION ALL SELECT period,'gift30 限时阅览券礼包',2,COUNT_IF(gift30_revenue>0),SUM(gift30_revenue) FROM user_panel GROUP BY 1 UNION ALL SELECT period,'gift31 限时阅览券礼包',3,COUNT_IF(gift31_revenue>0),SUM(gift31_revenue) FROM user_panel GROUP BY 1 UNION ALL SELECT period,'gift39 西索英雄试炼7日战令',4,COUNT_IF(gift39_revenue>0),SUM(gift39_revenue) FROM user_panel GROUP BY 1)
SELECT '卡池参与深度' analysis_type,d.period,d.segment,d.segment_order,d.users,d.payers,ROUND(CAST(d.payers AS DOUBLE)/NULLIF(d.users,0),4) segment_payer_rate,ROUND(d.revenue_usd,2) revenue_usd,ROUND(d.revenue_usd/NULLIF(d.payers,0),2) segment_arppu_usd,ROUND(d.revenue_usd/t.all_payers,2) arppu_contribution_usd,ROUND(d.avg_draws,1) avg_draws,t.active_users,t.all_payers FROM depth d JOIN totals t ON d.period=t.period
UNION ALL SELECT '指定礼包购买',s.period,s.segment,s.segment_order,CAST(NULL AS BIGINT),s.buyers,ROUND(CAST(s.buyers AS DOUBLE)/NULLIF(t.active_users,0),4),ROUND(s.revenue_usd,2),ROUND(s.revenue_usd/NULLIF(s.buyers,0),2),ROUND(s.revenue_usd/t.all_payers,2),CAST(NULL AS DOUBLE),t.active_users,t.all_payers FROM selected_product s JOIN totals t ON s.period=t.period ORDER BY 1,2,4;
