/* Same-user stock test for the Pain-week USD100+ core payer cohort. */
WITH blacklist AS (
  SELECT DISTINCT "#varchar_id" account_id FROM user_result_cluster_23 WHERE cluster_name IN ('internal_users','is_water','is_water_mod','suspicious_ip')
), wallet AS (
  SELECT CAST(lcxtransactionid AS VARCHAR) transaction_id, MAX(ABS(CAST(freeamount AS DOUBLE))) freeamount FROM ta.v_event_16 WHERE "$part_event"='LCX_WALLET_SPEND_TRANSACTION' AND "$part_date" BETWEEN '2026-07-15' AND '2026-08-04' GROUP BY 1
), revenue AS (
  SELECT period,account_id,SUM(revenue_usd) revenue_usd FROM (
    SELECT CASE WHEN v."$part_date" BETWEEN '2026-07-15' AND '2026-07-21' THEN '佩恩' ELSE '西索' END period,COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id") account_id,(CAST(JSON_EXTRACT_SCALAR(CAST(v.payload AS JSON),'$.curamt') AS DOUBLE)-COALESCE(w.freeamount,0))/COALESCE(x.exchange,1) revenue_usd
    FROM ta.v_event_23 v LEFT JOIN blacklist b ON COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=b.account_id LEFT JOIN wallet w ON CAST(JSON_EXTRACT_SCALAR(CAST(v.payload AS JSON),'$.purchaseid') AS VARCHAR)=w.transaction_id LEFT JOIN ta_dim.ta_exchange x ON v."$part_date"=x.ex_date AND JSON_EXTRACT_SCALAR(CAST(v.payload AS JSON),'$.cur')=x.currency
    WHERE v."$part_event"='PURCHASE' AND v."$part_date" BETWEEN '2026-07-15' AND '2026-08-04' AND COALESCE(CAST(JSON_EXTRACT_SCALAR(CAST(v.payload AS JSON),'$.validationtype') AS VARCHAR),'')<>'SANDBOX_RECEIPT' AND b.account_id IS NULL
  ) x GROUP BY 1,2
), pain_active AS (
  SELECT DISTINCT COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id") account_id FROM ta.v_event_23 v LEFT JOIN blacklist b ON COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=b.account_id WHERE v."$part_event"='LOGIN_SUCCESS' AND v."$part_date" BETWEEN '2026-07-15' AND '2026-07-21' AND b.account_id IS NULL
), core AS (
  SELECT r.account_id,CASE WHEN COALESCE(h.revenue_usd,0)=0 THEN '西索未付费' WHEN COALESCE(h.revenue_usd,0)<100 THEN '西索付费<$100' ELSE '西索仍≥$100' END hisoka_pay_state FROM revenue r JOIN pain_active a ON r.account_id=a.account_id LEFT JOIN revenue h ON r.account_id=h.account_id AND h.period='西索' WHERE r.period='佩恩' AND r.revenue_usd>=100
), core_groups AS (SELECT account_id,hisoka_pay_state FROM core UNION ALL SELECT account_id,'全体核心' FROM core), event_def AS (SELECT '佩恩活动前' phase,DATE '2026-07-15' start_date UNION ALL SELECT '西索活动前',DATE '2026-07-29'), balance_raw AS (
  SELECT c.hisoka_pay_state,e.phase,c.account_id,CAST(v.id AS INTEGER) resource_id,GREATEST(MAX_BY(CAST(v.after AS DOUBLE),CAST(v."#event_time" AS timestamp(3))),0) balance FROM core_groups c CROSS JOIN event_def e LEFT JOIN ta.v_event_23 v ON v."$part_event"='resource_change' AND v."$part_date" BETWEEN '2026-06-24' AND CAST(e.start_date - INTERVAL '1' DAY AS VARCHAR) AND COALESCE(v.fc_sdk_common.lcx_id,v.sdkcommon.lcx_id,v."#account_id")=c.account_id AND CAST(v.id AS INTEGER) IN (3,8,10) GROUP BY 1,2,3,4
), user_stock AS (
  SELECT hisoka_pay_state,phase,account_id,COALESCE(MAX(CASE WHEN resource_id=10 THEN balance END),0) ticket_balance,COALESCE(MAX(CASE WHEN resource_id=3 THEN balance END),0)+COALESCE(MAX(CASE WHEN resource_id=8 THEN balance END),0) star_balance FROM balance_raw GROUP BY 1,2,3
)
SELECT hisoka_pay_state,COUNT(DISTINCT account_id) core_users,ROUND(AVG(CASE WHEN phase='佩恩活动前' THEN ticket_balance END),2) pain_avg_ticket,ROUND(AVG(CASE WHEN phase='西索活动前' THEN ticket_balance END),2) hisoka_avg_ticket,ROUND(AVG(CASE WHEN phase='佩恩活动前' THEN star_balance END),2) pain_avg_star,ROUND(AVG(CASE WHEN phase='西索活动前' THEN star_balance END),2) hisoka_avg_star,ROUND(AVG(CASE WHEN phase='佩恩活动前' THEN ticket_balance+star_balance/150.0 END),2) pain_avg_potential_draws,ROUND(AVG(CASE WHEN phase='西索活动前' THEN ticket_balance+star_balance/150.0 END),2) hisoka_avg_potential_draws,APPROX_PERCENTILE(IF(phase='佩恩活动前',ticket_balance+star_balance/150.0,NULL),0.5) pain_p50_potential_draws,APPROX_PERCENTILE(IF(phase='西索活动前',ticket_balance+star_balance/150.0,NULL),0.5) hisoka_p50_potential_draws,ROUND(CAST(COUNT_IF(phase='佩恩活动前' AND ticket_balance+star_balance/150.0>=40) AS DOUBLE)/COUNT_IF(phase='佩恩活动前'),4) pain_40_draw_stock_rate,ROUND(CAST(COUNT_IF(phase='西索活动前' AND ticket_balance+star_balance/150.0>=40) AS DOUBLE)/COUNT_IF(phase='西索活动前'),4) hisoka_40_draw_stock_rate
FROM user_stock GROUP BY 1 ORDER BY CASE hisoka_pay_state WHEN '全体核心' THEN 0 WHEN '西索未付费' THEN 1 WHEN '西索付费<$100' THEN 2 ELSE 3 END;
